version: 2

build:
  os: ubuntu-22.04
  tools:
    nodejs: "18"
  commands:
    # "docs/" directory was created using the command to create the site:
    # npx create-docusaurus@latest docs classic
    #
    # Install Docusaurus dependencies
    - cd docusaurus/ && npm install
    # Build the site
    - cd docusaurus/ && npm run build
    # Copy generated files into Read the Docs directory
    - mkdir --parents _readthedocs/html/
    - cp --recursive docusaurus/build/* _readthedocs/html/
